# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/api/':
#             origin_regex: true
#             allow_origin: ['*'] # You probably want to change this regex to match your real domain
#             allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#             allow_headers: ['Content-Type', 'Authorization']
#             expose_headers: ['Link']
#             max_age: 3600
#         '^/images/':
#             origin_regex: true
#             allow_origin: ['*'] # You probably want to change this regex to match your real domain
#             allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#             allow_headers: ['*']
#             max_age: 3600
#             forced_allow_origin_value: '*'
        

nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['*'] # You probably want to change this regex to match your real domain
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link']
            max_age: 3600
# nelmio_cors:
#     defaults:
#         allow_credentials: false
#         allow_origin: []
#         allow_headers: []
#         allow_methods: []
#         expose_headers: []
#         max_age: 0
#         hosts: []
#         origin_regex: false
#         forced_allow_origin_value: ~
#     paths:
#         '^/images/':
#             origin_regex: true
#             allow_origin: ['*'] # You probably want to change this regex to match your real domain
#             allow_headers: ['*']
#             allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
#             max_age: 3600

#         '^/api/':
#             origin_regex: true
#             allow_origin: ['*'] # You probably want to change this regex to match your real domain
#             allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#             allow_headers: ['Content-Type', 'Authorization']
#             expose_headers: ['Link']
#             max_age: 3600